from __future__ import annotations

WORKFLOW_PARITY_MATRIX = [
    {
        "old_workflow": "import-fixtures-rolling.yml",
        "old_inputs": ["RapidAPI", "leagues-and-teams.json"],
        "old_outputs": ["match-for-date", "local fixture JSON"],
        "v2_job": "ingest_fixtures_window.py",
        "v2_outputs": ["raw_fixtures", "fixtures_canonical", "parity_reports"],
        "smoke_test": "ingest 1 day window twice, no duplicate canonical matches",
        "parity_proof": "compare per-date match counts, league counts, and match ids vs old match-for-date",
    },
    {
        "old_workflow": "import-fixtures-dplus7.yml",
        "old_inputs": ["RapidAPI", "leagues-and-teams.json"],
        "old_outputs": ["D+7 match-for-date"],
        "v2_job": "ingest_fixtures_window.py --days-ahead 7",
        "v2_outputs": ["raw_fixtures", "fixtures_canonical", "parity_reports"],
        "smoke_test": "ingest D+7 only",
        "parity_proof": "compare D+7 counts and missing leagues report",
    },
    {
        "old_workflow": "update-teamstats-and-teamprofiles.yml",
        "old_inputs": ["RapidAPI stats/incidents/shotmap/odds", "local teamstats dirs"],
        "old_outputs": ["teamstats", "job_state", "teamprofiles", "patched match-for-date"],
        "v2_job": "ingest_match_enrichment.py + build_teamprofiles.py",
        "v2_outputs": [
            "raw_match_statistics",
            "raw_incidents",
            "raw_shotmaps",
            "raw_results",
            "match_stats_canonical",
            "teamprofiles_v2",
        ],
        "smoke_test": "replay one finished match and one open match",
        "parity_proof": "compare teamstats match coverage, stat block availability, and profile counts per team/league",
    },
    {
        "old_workflow": "backfill-teamstats-from-date.yml",
        "old_inputs": ["RapidAPI", "backfill date"],
        "old_outputs": ["teamstats", "job_state"],
        "v2_job": "backfill_match_enrichment.py",
        "v2_outputs": ["raw_match_statistics", "raw_incidents", "raw_shotmaps", "raw_results", "job_runs"],
        "smoke_test": "backfill 1 explicit date",
        "parity_proof": "compare recovered match counts and unresolved matches list",
    },
    {
        "old_workflow": "verify-teamstats-db.yml",
        "old_inputs": ["Mongo", "job_state"],
        "old_outputs": ["verification log"],
        "v2_job": "verify_match_enrichment.py",
        "v2_outputs": ["health_reports", "audit_reports"],
        "smoke_test": "run after one ingest window",
        "parity_proof": "compare expected teamstats coverage thresholds and stale-run detection",
    },
    {
        "old_workflow": "dump-matchups.yml",
        "old_inputs": ["match-for-date", "teamprofiles"],
        "old_outputs": ["matchups-score", "matchups-league-avg", "local matchup JSON"],
        "v2_job": "build_matchups_score.py + build_matchups_league_avg.py",
        "v2_outputs": ["matchups_score_v2", "matchups_league_avg_v2", "parity_reports"],
        "smoke_test": "build one target date",
        "parity_proof": "compare row counts, top50 coverage, and stat/scope/period distribution",
    },
    {
        "old_workflow": "enrich-matchups-results.yml",
        "old_inputs": ["matchup collections", "teamstats", "RapidAPI fallback"],
        "old_outputs": ["enriched matchup outcomes"],
        "v2_job": "settle_matchups_outputs.py",
        "v2_outputs": ["matchups_score_v2", "matchups_league_avg_v2", "audit_reports"],
        "smoke_test": "settle one past date range",
        "parity_proof": "compare resolved outcome counts and unresolved reasons vs old",
    },
    {
        "old_workflow": "run-unibet-backtests.yml",
        "old_inputs": ["fixtures", "Unibet/Kambi", "EV engine"],
        "old_outputs": ["unibet-backtest snapshots"],
        "v2_job": "build_model_snapshots.py",
        "v2_outputs": ["raw_odds_kambi", "unibet_event_links", "market_offers", "model_snapshots"],
        "smoke_test": "process one date",
        "parity_proof": "compare matches processed, lines generated, missing-event rate, and checkpoint-neutral snapshot counts",
    },
    {
        "old_workflow": "run-unibet-forward.yml",
        "old_inputs": ["fixtures", "Unibet/Kambi"],
        "old_outputs": ["manual forward snapshot output"],
        "v2_job": "build_model_snapshots.py --mode forward",
        "v2_outputs": ["raw_odds_kambi", "unibet_event_links", "market_offers", "model_snapshots"],
        "smoke_test": "process one manual date",
        "parity_proof": "compare forward snapshot coverage vs old script",
    },
    {
        "old_workflow": "run-unibet-closing.yml",
        "old_inputs": ["near-kickoff fixtures", "Unibet/Kambi"],
        "old_outputs": ["closing captures in unibet-backtest style docs"],
        "v2_job": "capture_closing_snapshots.py",
        "v2_outputs": ["market_snapshots", "closing_lines_v2"],
        "smoke_test": "process one synthetic kickoff window",
        "parity_proof": "compare capture counts and valid prematch-only rate",
    },
    {
        "old_workflow": "run-unibet-odds-checkpoints.yml",
        "old_inputs": ["rolling fixtures", "existing snapshots"],
        "old_outputs": ["checkpointed odds in unibet-backtest"],
        "v2_job": "capture_odds_checkpoints.py",
        "v2_outputs": ["market_snapshots", "parity_reports", "audit_reports"],
        "smoke_test": "simulate due windows for T-3D/T-2D/T-1D/T-10M",
        "parity_proof": "compare due-match selection and snapshot counts; audit post-start exclusion",
    },
    {
        "old_workflow": "correct-backtests-daily.yml",
        "old_inputs": ["unibet-backtest", "teamstats"],
        "old_outputs": ["corrected lines.actual / lines.win"],
        "v2_job": "settle_model_snapshots.py",
        "v2_outputs": ["settled_bets_v2", "audit_reports"],
        "smoke_test": "settle one finished date",
        "parity_proof": "compare win/loss/push counts and unresolved reasons",
    },
    {
        "old_workflow": "run-auto-analysis-checkpoints.yml",
        "old_inputs": ["fixtures", "odds", "EV", "ranking feedback"],
        "old_outputs": ["auto-analysis-runs", "auto-analysis-bets", "analysis-snapshots"],
        "v2_job": "run_auto_analysis.py",
        "v2_outputs": ["analysis_runs_v2", "analysis_candidates_v2", "analysis_snapshots_v2"],
        "smoke_test": "run one checkpoint/date",
        "parity_proof": "compare analyzed matches, candidate counts, shortlist counts, and unmatched odds rate",
    },
    {
        "old_workflow": "ai-bets-daily.yml",
        "old_inputs": ["matchup outputs", "odds", "EV"],
        "old_outputs": ["ai-generated-bets"],
        "v2_job": "build_ai_bet_exports.py --mode daily",
        "v2_outputs": ["prediction_exports_v2"],
        "smoke_test": "run one date",
        "parity_proof": "compare total exported bets and match coverage",
    },
    {
        "old_workflow": "ai-user-combos.yml",
        "old_inputs": ["matchup outputs", "odds", "EV"],
        "old_outputs": ["combo-style ai-generated-bets"],
        "v2_job": "build_ai_bet_exports.py --mode combos",
        "v2_outputs": ["prediction_exports_v2"],
        "smoke_test": "run one date",
        "parity_proof": "compare combo counts and line source coverage",
    },
    {
        "old_workflow": "ai-user-daily.yml",
        "old_inputs": ["internal API calls over matchup/odds flows"],
        "old_outputs": ["AI-user generated bet docs"],
        "v2_job": "build_ai_bet_exports.py --mode user-daily",
        "v2_outputs": ["prediction_exports_v2"],
        "smoke_test": "run one date",
        "parity_proof": "compare line counts, started-match exclusion, and saved snapshot coverage",
    },
    {
        "old_workflow": "ai-user-closing.yml",
        "old_inputs": ["internal API calls over matchup/odds flows"],
        "old_outputs": ["AI-user closing refresh"],
        "v2_job": "build_ai_bet_exports.py --mode user-closing",
        "v2_outputs": ["prediction_exports_v2", "closing_lines_v2"],
        "smoke_test": "run one closing window",
        "parity_proof": "compare near-kickoff selection and closing capture rate",
    },
    {
        "old_workflow": "update-opta.yml",
        "old_inputs": ["Opta ranking JSON", "support files"],
        "old_outputs": ["updated support JSON"],
        "v2_job": "sync_support_data.py",
        "v2_outputs": ["support_sources", "support_leagues", "support_teams", "support_rankings"],
        "smoke_test": "sync once",
        "parity_proof": "compare league/team counts and Opta id/rank/rating fill rates",
    },
    {
        "old_workflow": "train-ml-models.yml",
        "old_inputs": ["corrected backtests", "Mongo extracts"],
        "old_outputs": ["training datasets", "trained model files"],
        "v2_job": "build_training_exports.py",
        "v2_outputs": ["training_exports_v2", "parity_reports"],
        "smoke_test": "export one bounded date range",
        "parity_proof": "compare sample counts and stat/scope/period coverage",
    },
    {
        "old_workflow": "debug-rapidapi-endpoints.yml",
        "old_inputs": ["RapidAPI envs"],
        "old_outputs": ["console diagnostics"],
        "v2_job": "audit_source_connectivity.py",
        "v2_outputs": ["health_reports", "audit_reports"],
        "smoke_test": "run against all configured endpoints",
        "parity_proof": "compare success/failure matrix and empty payload detection",
    },
]
