import { ArrowLeft, Clock3 } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { CheckpointTimeline } from '../components/CheckpointTimeline';
import { EntityLink } from '../components/EntityLink';
import { SignalCard } from '../components/SignalCard';
import { StateNotice } from '../components/StateNotice';
import { useMatchDetail } from '../data/queries';
import { formatExpectedRoi, formatKickoff, formatOdds, formatProbability } from '../domain/formatters';

function initials(name:string|null){if(!name)return'—';return name.split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]?.toLocaleUpperCase('sv-SE')??'').join('');}
function pct(value:number|null){return value===null?'—':`${value>0?'+':''}${value.toLocaleString('sv-SE',{maximumFractionDigits:2})} %`;}

export function MatchDetailPage(){
 const{matchId}=useParams();const detail=useMatchDetail(matchId);if(detail.isLoading)return <StateNotice state="loading" title="Hämtar match" detail="Läser match, marknader och statistik."/>;if(detail.isError||!detail.data)return <StateNotice state="failed" title="Matchen kunde inte läsas" detail="Matchen hittades inte eller datakällan kunde inte nås."/>;const data=detail.data;const match=data.match;
 return <div className="page-stack">
  <Link to="/oversikt" className="back-link"><ArrowLeft size={15}/>Till översikt</Link>
  <section className="match-hero"><div className="match-hero__meta"><EntityLink kind="league" id={match.leagueKey}>{match.leagueName??'Liga saknas'}</EntityLink>{match.startTime?<span><Clock3 size={14}/>{formatKickoff(match.startTime)}</span>:null}</div><div className="team-versus"><EntityLink className="team-block" kind="team" id={match.homeTeamKey}><span className="team-monogram">{initials(match.homeTeamName)}</span><strong>{match.homeTeamName??'Okänt lag'}</strong></EntityLink><span className="versus-badge">{match.homeScore!==null&&match.awayScore!==null?`${match.homeScore}–${match.awayScore}`:'VS'}</span><EntityLink className="team-block team-block--right" kind="team" id={match.awayTeamKey}><span className="team-monogram">{initials(match.awayTeamName)}</span><strong>{match.awayTeamName??'Okänt lag'}</strong></EntityLink></div></section>
  <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Matchups</p><h2>Ranking för matchen</h2></div></div>{data.matchups.length?<div className="detail-signal-grid">{data.matchups.map((row)=><SignalCard key={row.entryKey} signal={row}/>)}</div>:<StateNotice state="empty" title="Ingen matchup-ranking" detail="Ingen ranking finns för matchen."/>}</section>
  <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Marknad</p><h2>Marknadsodds</h2></div></div>{data.marketOffers.length===0?<StateNotice state="empty" title="Inga marknadsodds" detail="Inga aktuella canonical market offers finns för matchen."/>:<div className="market-table"><div className="market-row market-row--head"><span>Marknad</span><span>Line</span><span>Over</span><span>Under</span><span>Källa</span></div>{data.marketOffers.map((row,index)=><div className="market-row" key={row.offerKey??`${row.statKey}:${row.scope}:${row.period}:${row.line}:${index}`}><strong>{row.statKey??'—'} · {row.scope??'—'} · {row.period??'—'}</strong><span>{row.line?.toLocaleString('sv-SE')??'—'}</span><span>{formatOdds(row.overOdds)}</span><span>{formatOdds(row.underOdds)}</span><span>{row.sourceProvider??'—'}</span></div>)}</div>}</section>
  <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Oddsflöde</p><h2>Checkpoint-tidslinje</h2></div></div>{data.checkpoints.length?<CheckpointTimeline checkpoints={data.checkpoints}/>:<StateNotice state="empty" title="Inga checkpoints för matchen" detail="Saknade snapshots fylls inte i."/>}</section>
  <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Lagstatistik</p><h2>Lagjämförelse</h2></div></div>{data.teamStats.length===0?<StateNotice state="empty" title="Lagstatistik saknas" detail="Inga värden uppskattas i frontend."/>:<div className="stats-table"><div className="stats-row stats-row--head"><span>Stat / period</span><span>{match.homeTeamName}</span><span>{match.awayTeamName}</span><span>Ligasnitt H / B</span></div>{data.teamStats.map((row)=><div className="stats-row" key={`${row.statKey}:${row.period}`}><strong>{row.statKey} · {row.period}</strong><span>{row.homeValue?.toLocaleString('sv-SE')??'—'}{row.homeRank!==null?` (#${row.homeRank})`:''}</span><span>{row.awayValue?.toLocaleString('sv-SE')??'—'}{row.awayRank!==null?` (#${row.awayRank})`:''}</span><span>{row.homeLeagueAverage?.toLocaleString('sv-SE')??'—'} / {row.awayLeagueAverage?.toLocaleString('sv-SE')??'—'}</span></div>)}</div>}</section>
  {data.actualStats.length?<section className="content-section"><div className="section-heading"><div><p className="eyebrow">Utfall</p><h2>Faktiska matchvärden</h2></div></div><div className="actual-grid">{data.actualStats.map((row,index)=><article key={`${row.statKey}:${row.period}:${row.scope}:${index}`}><span>{row.statKey} · {row.scope} · {row.period}</span><strong>{row.actualValue?.toLocaleString('sv-SE')??'—'}</strong></article>)}</div></section>:null}
  <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Forward</p><h2>Utfall & forward-evidens</h2></div></div>{data.forwardSelections.length===0&&data.forwardResults.length===0?<StateNotice state="empty" title="Ingen registrerad forward-evidens" detail="Matchup-ranking är analysdata och visas inte som ett registrerat spel."/>:<div className="evidence-list">{data.forwardSelections.map((row)=><article className="evidence-row" key={row.selectionKey??row.predictionKey??'selection'}><div><strong>{row.direction?.toUpperCase()} {row.statKey} · {row.scope} · {row.period}</strong><small>Line {row.lineValue??'—'} · odds {formatOdds(row.selectedOdds)}</small></div><span>Modell P {formatProbability(row.predictedWinProbability)}</span><span>EV {formatExpectedRoi(row.expectedRoiUnits)}</span></article>)}{data.forwardResults.map((row)=><article className="evidence-row evidence-row--settled" key={row.resultLoopKey??row.predictionKey??'result'}><div><strong>{row.settlementResult?.toUpperCase()??row.resultLoopStatus??'Resultat'}</strong><small>Actual {row.actualValue??'—'} · PnL {row.pnlUnits??'—'}u</small></div><span>{row.officialClv?`CLV ${pct(row.clvPct)}`:'CLV saknas'}</span><span>{row.closingOdds!==null?`Close ${formatOdds(row.closingOdds)}`:'Closing saknas'}</span></article>)}</div>}</section>
 </div>;
}
