from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ullebets_v2.config import V2Config
from ullebets_v2.model_snapshots.ephemeral import build_ephemeral_model_read_database
from ullebets_v2.model_snapshots.oracle import OriginalJsModelOracle, V2JsModelOracle
from ullebets_v2.model_snapshots.runtime_parity import run_model_snapshot_runtime_parity_audit
from ullebets_v2.odds.service import load_legacy_backtest_targets, load_replay_fixture_targets
from ullebets_v2.safety import ensure_v2_database
from ullebets_v2.storage.mongo import get_database, get_legacy_app_database
from ullebets_v2.support.loaders import load_support_documents


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare legacy historical snapshot lines against lines generated by the V2-owned snapshot runtime."
    )
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--date", dest="dates", action="append", default=[])
    parser.add_argument("--snapshot-mode", choices=["backtest", "forward", "closing"], default="backtest")
    parser.add_argument("--target-source", choices=["replay-fixtures", "legacy-backtest"], default="replay-fixtures")
    parser.add_argument("--source-workflow")
    parser.add_argument("--leagues-path", type=Path)
    parser.add_argument("--league-urls-path", type=Path)
    parser.add_argument("--teamstats-dir", type=Path)
    parser.add_argument(
        "--use-original-model-oracle",
        action="store_true",
        help="Compare the legacy repo JS model runtime instead of the V2-owned runtime.",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.dates:
        raise RuntimeError("At least one --date is required.")
    config = V2Config.from_env(args.repo_root)
    ensure_v2_database(config)
    config.ensure_directories()

    support_docs = load_support_documents(
        leagues_path=args.leagues_path or config.default_leagues_path(),
        league_urls_path=args.league_urls_path or config.default_league_urls_path(),
    )
    legacy_app_database = get_legacy_app_database(config)
    if args.target_source == "legacy-backtest":
        targets = load_legacy_backtest_targets(
            dates=args.dates,
            support_docs=support_docs,
            legacy_backtest_database=legacy_app_database,
            legacy_match_database=legacy_app_database,
            limit=args.limit,
        )
    else:
        targets = load_replay_fixture_targets(
            dates=args.dates,
            support_docs=support_docs,
            old_repo_root=config.old_repo_root,
            legacy_match_database=legacy_app_database,
        )
    teamstats_dir = args.teamstats_dir or (config.old_repo_root / "data" / "teamstats")
    if args.use_original_model_oracle:
        read_database = get_database(config)
    elif teamstats_dir.exists():
        read_database = build_ephemeral_model_read_database(
            teamstats_dir=teamstats_dir,
            support_docs=support_docs,
            targets=targets,
        )
    else:
        read_database = get_database(config)

    source_workflow = args.source_workflow or (
        "run-unibet-backtests.yml"
        if args.snapshot_mode == "backtest"
        else "run-unibet-forward.yml"
        if args.snapshot_mode == "forward"
        else "run-unibet-closing.yml"
    )
    model_oracle = (
        OriginalJsModelOracle(config.old_repo_root)
        if args.use_original_model_oracle
        else V2JsModelOracle(read_database, support_docs)
    )
    summary = run_model_snapshot_runtime_parity_audit(
        targets=targets,
        support_docs=support_docs,
        source_workflow=source_workflow,
        snapshot_mode=args.snapshot_mode,
        legacy_backtest_database=legacy_app_database,
        model_oracle=model_oracle,
        target_source=args.target_source,
        database=None if args.dry_run else read_database,
        dry_run=args.dry_run,
        return_documents=True,
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
